"""modificando atributo password en usuario

Revision ID: 00af3ad32097
Revises: 4750952d679f
Create Date: 2025-03-31 02:03:48.991437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00af3ad32097'
down_revision = '4750952d679f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
