"""drop description for permission

Revision ID: 4750952d679f
Revises: 51a0552eead3
Create Date: 2025-03-30 16:06:06.074434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4750952d679f'
down_revision = '51a0552eead3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
