"""editando modelo usuario

Revision ID: d83d7dfdc083
Revises: 00af3ad32097
Create Date: 2025-04-04 00:50:41.821335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83d7dfdc083'
down_revision = '00af3ad32097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.drop_constraint('usuarios_username_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint('usuarios_username_key', ['username'])
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
